version: "3"

services:
  postgresdb:
    build:
      context: ../docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ../docker/postgres/init.sql:/docker-entrypoint-iitdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
